export const CHANGE_HEADER="CHANGE_HEADER"
export const SESSION_START="SESSION_START"
export const SESSION_DESTROY="SESSION_DESTROY"
export const DIPLAY_LOGIN_FORM="DIPLAY_LOGIN_FORM"
export const DIPLAY_REGISTER_FORM="DIPLAY_REGISTER_FORM"



